{
 "title": "Ack Pro ApiServer",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "verb",
    "query": {
     "query": "label_values(apiserver_request_total, verb)"
    }
   },
   {
    "name": "resource",
    "query": {
     "query": "label_values(apiserver_request_total, resource)"
    }
   },
   {
    "name": "client",
    "query": {
     "query": "label_values(apiserver_request_total, client)"
    }
   },
   { "name": "quantile", "query": "0.99,0.9,0.5" },
   { "name": "interval", "query": "1m,5m,10m" }
  ]
 },
 "panels": [
  {
   "title": "API QPS",
   "type": "stat",
   "description": "当前集群的每秒请求数总量（包括全部读写请求）",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(apiserver_request_total[$interval]))"
    }
   ]
  },
  {
   "title": "Read Request Success Rate",
   "type": "stat",
   "description": "每秒的读请求成功率",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(apiserver_request_total{code=~\"20.*\",verb=~\"GET|LIST\"}[$interval]))/sum(irate(apiserver_request_total{verb=~\"GET|LIST\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Mutating Request Success Rate",
   "type": "stat",
   "description": "每秒的修改请求的成功率",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(apiserver_request_total{code=~\"20.*\",verb!~\"GET|LIST|WATCH|CONNECT\"}[$interval]))/sum(irate(apiserver_request_total{verb!~\"GET|LIST|WATCH|CONNECT\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Read InFlight Requests",
   "type": "stat",
   "description": "集群内在处理的读请求总量",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(apiserver_current_inflight_requests{requestKind=\"readOnly\"})"
    }
   ]
  },
  {
   "title": "Mutating InFlight Requests",
   "type": "stat",
   "description": "集群内在处理的写请求总量",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " sum(apiserver_current_inflight_requests{requestKind=\"mutating\"})"
    }
   ]
  },
  {
   "title": "Dropped Requests Rate",
   "type": "stat",
   "description": "因为写请求水位过高导致每秒拒绝请求的总量",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(apiserver_dropped_requests_total[$interval]))"
    }
   ]
  },
  { "title": "Cluster-Level Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Read(Non-LIST) Request Latency(GET) P[$quantile]",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum(irate(apiserver_request_duration_seconds_bucket{verb=\"GET\",resource!=\"\"}[$interval])) by (pod, verb, resource, scope, le))",
     "legendFormat": "{{pod}} - {{verb}} - {{resource}}  - {{scope}}"
    }
   ]
  },
  {
   "title": "Read(LIST) Request Latency P[$quantile]",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum(irate(apiserver_request_duration_seconds_bucket{verb=\"LIST\"}[$interval])) by (pod_name, verb, resource, scope, le)) ",
     "legendFormat": "{{pod_name}} - {{verb}} - {{resource}}  - {{scope}}"
    }
   ]
  },
  {
   "title": "Mutating Request Latency P[$quantile]",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum(irate(apiserver_request_duration_seconds_bucket{verb!~\"GET|WATCH|LIST|CONNECT\"}[$interval])) by (cluster, pod_name, verb, resource, scope, le))",
     "legendFormat": "{{pod_name}} - {{verb}} - {{resource}}  - {{scope}}"
    }
   ]
  },
  {
   "title": "ReadOnly Inflight Request ",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "apiserver_current_inflight_requests{requestKind=\"readOnly\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Mutating Inflight Request ",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "apiserver_current_inflight_requests{requestKind=\"mutating\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Apiserver Dropped Request ",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(apiserver_dropped_requests_total[$interval])) by (name)",
     "legendFormat": "{{name}}  - drop rate"
    }
   ]
  },
  { "title": "QPS & Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "QPS By Verb [$verb] P[$quantile] ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(apiserver_request_total{verb=~\"$verb\"}[$interval]))by(verb)",
     "legendFormat": " {{verb}} "
    }
   ]
  },
  {
   "title": "QPS by Verb + Resource P[$quantile] [$resource]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(apiserver_request_total{verb=~\"$verb\",resource=~\"$resource\"}[$interval]))by(verb,resource)",
     "legendFormat": "{{verb}} - {{resource}}"
    },
    {}
   ]
  },
  {
   "title": "Latency by Verb [$verb] P[$quantile] ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum(irate(apiserver_request_duration_seconds_bucket{verb=~\"$verb\", verb!~\"WATCH|CONNECT\",resource!=\"\"}[$interval])) by (le,verb))",
     "legendFormat": "{{verb}}"
    }
   ]
  },
  {
   "title": "Latency by Verb + Resource [$resource] P[$quantile] ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum(irate(apiserver_request_duration_seconds_bucket{verb=~\"$verb\", verb!~\"WATCH|CONNECT\", resource=~\"$resource\",resource!=\"\"}[$interval])) by (le,verb,resource))",
     "legendFormat": "{{verb}} - {{resource}}"
    }
   ]
  },
  {
   "title": "Response Error For Read [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(apiserver_request_total{verb=~\"GET|LIST\",resource=~\"$resource\",code!~\"2.*\"}[$interval])) by (verb,resource,code)",
     "legendFormat": "{{verb}}/{{resource}} {{code}} "
    }
   ]
  },
  {
   "title": "Response Error For Mutating [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(apiserver_request_total{verb!~\"GET|LIST|WATCH\",verb=~\"$verb\",resource=~\"$resource\",code!~\"2.*\"}[$interval])) by (verb,resource,code)",
     "legendFormat": "{{verb}}/{{resource}} {{code}} "
    }
   ]
  },
  { "title": "Client Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "QPS By Client",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(apiserver_request_total[$interval])) by (client)",
     "legendFormat": "{{client}}"
    }
   ]
  },
  {
   "title": "QPS By Verb + Resource + Client [$verb]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(apiserver_request_total{verb=~\"$verb\", resource=~\"$resource\"}[$interval]))by(verb,resource,client)",
     "legendFormat": "{{verb}} - {{resource}} - {{client}}"
    }
   ]
  }
 ]
}