{
 "title": "Node TopN",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "60s",
 "panels": [
  {
   "title": "Node Top 5 Memory Usage/ %",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "topk(5,(1 - (node_memory_MemAvailable_bytes{ } / (node_memory_MemTotal_bytes)))* 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Top 5 Memory/GB",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "topk(5,((node_memory_MemTotal_bytes  - node_memory_MemAvailable_bytes )/1024/1024/1024))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Top 5 Memory Total/GB",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "topk(5,((node_memory_MemTotal_bytes )/1024/1024/1024))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Top 5 Memory requests/ %",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "topk(5,sum(kube_pod_container_resource_requests_memory_bytes*100) by (node) / sum(kube_node_status_allocatable_memory_bytes) by (node))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Node Top 5 Cpu Usage/ %",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "topk(5,100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) by (instance) * 100))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Top 5 Cpu/ core",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "targets": [
    {
     "expr": "topk(5,((100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) by (instance) * 100))*count(node_cpu_seconds_total{ mode='system'}) by (instance)/100))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Top 5 Cpu Total/ %",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "topk(5,count(node_cpu_seconds_total{ mode='system'}) by (instance)  )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Top 5 Cpu requests/ %",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "targets": [
    {
     "expr": "topk(5,sum(kube_pod_container_resource_requests_cpu_cores*100) by (node) / sum(kube_node_status_capacity_cpu_cores) by (node))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Node Top 5 load1",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "targets": [
    { "expr": "topk(5,node_load1)", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Node Top 5 net in ",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
   "targets": [
    {
     "expr": "topk(5,irate(node_network_receive_bytes_total{}[5m])*8)",
     "legendFormat": "{{instance}}/{{device}}_in"
    }
   ]
  },
  {
   "title": "Node Top 5 net out ",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "topk(5,irate(node_network_transmit_bytes_total{}[5m])*8)",
     "legendFormat": "{{instance}}/{{device}}_in"
    }
   ]
  },
  {
   "title": "Node Top 5 Disk usage / %",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 12 },
   "targets": [
    {
     "expr": "topk(5,(1-(sum(node_filesystem_free_bytes{}) by(instance,device) / sum(node_filesystem_size_bytes{}) by(instance,device)))*100)",
     "legendFormat": "{{instance}}/{{device}}"
    }
   ]
  }
 ]
}