{
 "title": "Pod-v4",
 "description": "Monitors Kubernetes cluster using Prometheus. Shows overall cluster CPU / Memory / Filesystem usage as well as individual pod, containers, systemd services statistics. Uses cAdvisor metrics only.",
 "tags": [ "arms-k8s" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "60s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "Pod",
    "label": "Pod",
    "query": "label_values(kube_pod_info{namespace=~'$namespace'} ,pod)"
   },
   {
    "name": "Pod_ip",
    "label": "Pod Ip",
    "query": "label_values(kube_pod_info{pod=~'$Pod'} ,pod_ip)"
   },
   {
    "name": "phase",
    "query": "query_result(kube_pod_status_phase{pod=~'$Pod'} >= 1)"
   },
   {
    "name": "container",
    "query": "label_values(kube_pod_container_info{pod=~'$Pod'} ,container)"
   },
   {
    "name": "Instance",
    "query": "label_values(container_cpu_usage_seconds_total{namespace='$namespace', pod_name='$Pod'} ,instance)"
   }
  ]
 },
 "panels": [
  { "title": "Pod Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Pod IP Address", "type": "text", "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 }, "options": { "content": "# $Pod_ip" } },
  {
   "title": "Pod Status",
   "type": "text",
   "description": "Pods that have been deleted cannot be queried.",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "options": {
    "content": "# status:' $phase ' pod:' $Pod '"
   }
  },
  { "title": "Pod Container", "type": "text", "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 }, "options": { "content": "# $container" } },
  {
   "title": "Container restarts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{pod=\"$Pod\"})"
    }
   ]
  },
  { "title": "Network I/O pressure", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Network I/O pressure",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",pod_name=\"$Pod\",namespace=\"$namespace\"}[1m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",pod_name=\"$Pod\",namespace=\"$namespace\"}[1m]))",
     "legendFormat": "Sent"
    }
   ]
  },
  { "title": "Total usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Pod memory utilization",
   "type": "gauge",
   "description": "When the pod have resource limit. \nPod Memory Utilization = working_set / pod_memory_limit\n\nwhen the pod limit is empty. \nPod Memory Utilization = working_set / machine_memory_capacity(the node which pod on)\n",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",pod_name=\"$Pod\",namespace=\"$namespace\"}) / \n\n(\n (sum (container_spec_memory_limit_bytes{image!=\"\",pod_name=\"$Pod\",namespace=\"$namespace\"}) != bool 0)*\n (sum (container_spec_memory_limit_bytes{image!=\"\",pod_name=\"$Pod\",namespace=\"$namespace\"})) +\n (sum (container_spec_memory_limit_bytes{image!=\"\",pod_name=\"$Pod\",namespace=\"$namespace\"}) == bool 0)*\n (sum (machine_memory_bytes{instance=\"$Instance\"})) \n\n)\n* 100\n\n\n\n\n"
    }
   ]
  },
  {
   "title": "Pod CPU utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\",pod_name=\"$Pod\",namespace=\"$namespace\"}[1m])) by (pod_name, namespace) / (sum(container_spec_cpu_quota{image!=\"\",pod_name=\"$Pod\",namespace=\"$namespace\"}/100000) by (pod_name, namespace)) * 100\n"
    }
   ]
  },
  {
   "title": "Pod Mem Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",pod_name=\"$Pod\",namespace=\"$namespace\"})\n"
    }
   ]
  },
  {
   "title": "Machine Mem Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(\n (sum (container_spec_memory_limit_bytes{image!=\"\",pod_name=\"$Pod\",namespace=\"$namespace\"}) != bool 0)*\n (sum (container_spec_memory_limit_bytes{image!=\"\",pod_name=\"$Pod\",namespace=\"$namespace\"})) +\n (sum (container_spec_memory_limit_bytes{image!=\"\",pod_name=\"$Pod\",namespace=\"$namespace\"}) == bool 0)*\n (sum (machine_memory_bytes{instance=\"$Instance\"})) \n\n)"
    }
   ]
  },
  {
   "title": "Pod CPU Usage Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Cores" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",pod_name=\"$Pod\",namespace=\"$namespace\"}[1m]))"
    }
   ]
  },
  {
   "title": "Machine CPU Usage Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Cores" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",namespace=\"$namespace\"}[1m]))"
    }
   ]
  },
  {
   "title": "Pod Mem Request",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (kube_pod_container_resource_requests_memory_bytes{pod_name=\"$Pod\", namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Pod Mem Limit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (kube_pod_container_resource_limits_memory_bytes{pod_name=\"$Pod\", namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Pod CPU Resource Request",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Cores" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (kube_pod_container_resource_requests_cpu_cores{pod_name=\"$Pod\",namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Pod CPU Resource Limit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Cores" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (kube_pod_container_resource_limits_cpu_cores{pod_name=\"$Pod\",namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Pods CPU usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods CPU usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",pod_name=\"$Pod\",namespace=\"$namespace\"}[1m])) by (pod_name)",
       "legendFormat": "{{ pod_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "All processes CPU usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "All processes CPU usage",
     "type": "graph",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id!=\"/\",image!=\"\",pod_name=\"$Pod\",namespace=\"$namespace\"}[1m])) by (id)",
       "legendFormat": "{{ id }}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU Throttle",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Throttle Rate",
     "type": "graph",
     "description": "Warning when CPU Throttle Rate greater than 25%.\n\nWe recomand to settle: https://help.aliyun.com/document_detail/178168.html\n",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (container, pod, namespace) (rate(container_cpu_cfs_throttled_periods_total{container!=\"\", namespace=\"$namespace\", pod=\"$Pod\"}[1m])) / sum by (container, pod, namespace) (rate(container_cpu_cfs_periods_total{namespace=\"$namespace\", pod=\"$Pod\"}[1m]))\n",
       "legendFormat": "[Pod] {{ pod }} [Container] {{ container }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods memory usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods memory usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{image!=\"\",pod_name=\"$Pod\",namespace=\"$namespace\"}) by (pod_name)",
       "legendFormat": "{{ pod_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "All processes memory usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "All processes memory usage",
     "type": "graph",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id!=\"/\",image!=\"\",pod_name=\"$Pod\",namespace=\"$namespace\"}) by (id)",
       "legendFormat": "{{ id }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods network I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods network I/O",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",pod_name=\"$Pod\",namespace=\"$namespace\"}[1m])) by (pod_name)",
       "legendFormat": "-> {{ pod_name }}"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",pod_name=\"$Pod\",namespace=\"$namespace\"}[1m])) by (pod_name)",
       "legendFormat": "<- {{ pod_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "All processes network I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "All processes network I/O",
     "type": "graph",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",id!=\"/\",pod_name=\"$Pod\",namespace=\"$namespace\"}[1m])) by (id)",
       "legendFormat": "-> {{ id }}"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",id!=\"/\",pod_name=\"$Pod\",namespace=\"$namespace\"}[1m])) by (id)",
       "legendFormat": "<- {{ id }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Container info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Saturation rate",
     "type": "graph",
     "description": "如果您定义了CPU的 limit 值，计算饱和度将变得容易得多。\n当容器超出其CPU限制时，Linux运行时将“限制”该容器并在container_cpu_cfs_throttled_seconds_total指标中记录其被限制的时间",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(\n    rate(container_cpu_cfs_throttled_seconds_total{namespace=\"$namespace\" ,pod_name=\"$Pod\"}[5m])) \nby (container,pod_name)"
      }
     ]
    },
    {
     "title": "pod terminated reason",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": " sum (kube_pod_container_status_terminated_reason{namespace=\"$namespace\" , pod_name=\"$Pod\"}) by (reason ,pod_name , container) "
      }
     ]
    }
   ]
  }
 ]
}