{
 "title": "Prometheus",
 "description": "for prometheus scrape troubleshooting . \nhttps://arms.console.aliyun.com/#/prom/plugin\n",
 "tags": [ "arms-k8s" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "60s",
 "templating": {
  "list": [
   { "name": "job", "label": "job", "query": "label_values(up, job)" },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(up{job='$job'}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "抓取特别慢 Top 10 的问题机器列表",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk (10,scrape_duration_seconds)>10"
    }
   ]
  },
  {
   "title": "分布式抓取监控",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(up) by(_ARMS_AGENT_ID)" },
    {
     "expr": "sum (scrape_samples_scraped) by (_ARMS_AGENT_ID)"
    }
   ]
  },
  {
   "title": "SD  Instance/Job",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum (up) by (job)" }
   ]
  },
  {
   "title": "Scrape Rt/Job",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg (scrape_duration_seconds) by (job)"
    }
   ]
  },
  {
   "title": "Scrape Rt ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "-sum (up)" },
    { "expr": "sum (scrape_duration_seconds)" }
   ]
  },
  {
   "title": "Scrape Sample",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum (scrape_samples_scraped)" },
    {
     "expr": "-sum (scrape_samples_post_metric_relabeling)"
    }
   ]
  },
  {
   "title": "Scrape Rt / instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (scrape_duration_seconds{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Scrape Rt / instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (scrape_duration_seconds{job=\"$job\"}) by (instance)"
    }
   ]
  },
  {
   "title": "Scrape Sample Total / Job",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg (scrape_samples_scraped) by (job)"
    }
   ]
  },
  {
   "title": "Scrape Relabel Sample Total / Job",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg (scrape_samples_post_metric_relabeling) by (job)"
    }
   ]
  },
  {
   "title": "Scrape Sample Total / instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (scrape_samples_scraped{job='$job'}) by (instance)"
    }
   ]
  },
  {
   "title": "Scrape Relabel Sample Total / Instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (scrape_samples_post_metric_relabeling{job='$job'}) by (instance)"
    }
   ]
  },
  {
   "title": "Total Series Add / Job",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(scrape_series_added) by (job)"
    }
   ]
  },
  {
   "title": "Total Series Add / Instance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (scrape_series_added{job='$job'}) by (instance)"
    }
   ]
  },
  {
   "title": "SD  Instance/Job",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum (up) by (job)" }
   ]
  },
  {
   "title": "Scrape Rt/Job",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg (scrape_duration_seconds) by (job)"
    }
   ]
  }
 ]
}