{
 "title": "Kapp Alert",
 "description": "Dashboard for Micrometer(Java, Spring Boot, Actuator)",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ns",
    "label": "ns",
    "query": {
     "query": "label_values(container_memory_usage_bytes{}, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(container_memory_usage_bytes{namespace=\"$ns\", container!='POD', pod_source=\"eci\"}, pod)"
    }
   },
   {
    "name": "jvm_memory_pool_heap",
    "label": "JVM Memory Pools Heap",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{namespace=\"$ns\", pod=\"$pod\", area=\"heap\"},id)"
    }
   },
   {
    "name": "jvm_memory_pool_nonheap",
    "label": "JVM Memory Pools Non-Heap",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{namespace=\"$ns\", pod=\"$pod\", area=\"nonheap\"},id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Quick Facts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "pod" },
  {
   "title": "Uptime $pod",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{namespace='$ns', pod='$pod'}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Start time $pod",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{namespace='$ns', pod='$pod'}*1000",
     "legendFormat": "Uptime_{{pod}}"
    }
   ]
  },
  {
   "title": "Cpu load 10s $pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "avg(container_cpu_load_average_10s{namespace='$ns', pod='$pod', metrics_path=\"/metrics/cadvisor\"})/1000",
     "legendFormat": "CPU Load"
    }
   ]
  },
  {
   "title": " Heap used $pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\",namespace='$ns',pod='$pod'})*100/sum(jvm_memory_max_bytes{area=\"heap\"})",
     "legendFormat": "HeapUsed"
    }
   ]
  },
  {
   "title": "Non-Heap used $pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"nonheap\",namespace='$ns',pod='$pod'})*100/sum(jvm_memory_max_bytes{area=\"nonheap\",namespace='$ns',pod='$pod'})",
     "legendFormat": "Non-HeapUsage"
    }
   ]
  },
  { "title": "JVM Memory Pools (Heap)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 }, "repeat": "pod" },
  {
   "title": "$jvm_memory_pool_heap $pod",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 20 },
   "repeat": "jvm_memory_pool_heap",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_committed_bytes{namespace='$ns', pod=\"$pod\", id=\"$jvm_memory_pool_heap\"}",
     "legendFormat": "commited"
    },
    {
     "expr": "jvm_memory_max_bytes{namespace='$ns', pod=\"$pod\", id=\"$jvm_memory_pool_heap\"}",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "JVM Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "JVM Heap",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{namespace='$ns',pod='$pod', area=\"heap\"})",
     "legendFormat": "heap_used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{namespace='$ns',pod='$pod', area=\"heap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{namespace='$ns',pod='$pod', area=\"heap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Non-Heap",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{namespace='$ns',pod='$pod', area=\"nonheap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{namespace='$ns',pod='$pod', area=\"nonheap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{namespace='$ns',pod='$pod',area=\"nonheap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{namespace='$ns',pod='$pod'})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{namespace='$ns',pod='$pod'})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{namespace='$ns',pod='$pod'})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Heap Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(jvm_memory_used_bytes{namespace='$ns',pod='$pod', area='heap'})* 100) /sum(jvm_memory_max_bytes{namespace='$ns',pod='$pod', area='heap'}) ",
     "legendFormat": "heap_usage"
    }
   ]
  },
  {
   "title": "Non Heap Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(jvm_memory_used_bytes{application='kweb', area='nonheap'})* 100) /sum(jvm_memory_max_bytes{application='kweb', area='nonheap'}) ",
     "legendFormat": "nonheap_usage"
    }
   ]
  },
  { "title": "JVM Memory Pools (Non-Heap)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 }, "repeat": "pod" },
  {
   "title": "$jvm_memory_pool_nonheap $pod",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 49 },
   "repeat": "jvm_memory_pool_nonheap",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{namespace=\"$ns\", pod=\"$pod\", id=\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_committed_bytes{namespace=\"$ns\", pod=\"$pod\", id=\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "commited "
    },
    {
     "expr": "jvm_memory_max_bytes{namespace=\"$ns\", pod=\"$pod\", id=\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "Dubbo Requests Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Dubbo Request Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum by (interface) (increase(dubbo_request_success_total{namespace='$ns', pod='$pod'}[2m])/120))/(sum by (interface) (increase(dubbo_request_total{namespace='$ns', pod='$pod'}[2m])/120))",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "Dubbo Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (interface, method) (dubbo_request_latency_seconds{namespace='$ns', pod='$pod', quantile='0.9'}*1000)",
     "legendFormat": "{{interface}}_{{method}}"
    }
   ]
  },
  {
   "title": "Dubbo Request Concurrent",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 59 },
   "targets": [
    {
     "expr": "sum by (interface) (increase(dubbo_request_concurrent_total{namespace='$ns', pod='$pod'}[2m])/120)",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  { "title": "HttpRequests Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Http Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (uri) (rate(http_server_requests_seconds_count{namespace='$ns', pod=\"$pod\"}[2m]))",
     "legendFormat": "HTTP_{{uri}}"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (uri) (rate(http_server_requests_seconds_sum{namespace='$ns', pod='$pod', status!~\"5..\"}[2m]))/sum by (uri) (rate(http_server_requests_seconds_count{namespace='$ns', pod='$pod', status!~\"5..\"}[2m]))",
     "legendFormat": "HTTP_AVG_{{uri}}"
    },
    {
     "expr": "max by (uri) (http_server_requests_seconds_max{namespace='$ns', pod='$pod', status!~\"5..\"})",
     "legendFormat": "HTTP_MAX_{{uri}}"
    }
   ]
  },
  {
   "title": "Http-Errors-5xx",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (uri) (rate(http_server_requests_seconds_count{namespace='$ns', pod='$pod', status=~\"5..\"}[2m]))",
     "legendFormat": "HTTP_5xx_{{uri}}"
    }
   ]
  },
  { "title": "Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "Collections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg by (action, cause) (rate(jvm_gc_pause_seconds_count{namespace='$ns', pod='$pod'}[2m]))",
     "legendFormat": "{{action}} ({{cause}})"
    },
    {
     "expr": "avg by (cause) (rate(jvm_gc_pause_seconds_count{namespace='$ns', pod='$pod', action=\"end of major GC\"}[2m]))",
     "legendFormat": "MajorGC"
    }
   ]
  },
  {
   "title": "Pause Durations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (action, cause) (rate(jvm_gc_pause_seconds_sum{namespace='$ns', pod='$pod'}[2m])/rate(jvm_gc_pause_seconds_count{namespace='$ns', pod='$pod'}[2m]))",
     "legendFormat": "avg {{action}} ({{cause}})"
    },
    {
     "expr": "avg by (action, cause) (jvm_gc_pause_seconds_max{namespace='$ns', pod='$pod'})",
     "legendFormat": "max {{action}} ({{cause}})"
    }
   ]
  },
  {
   "title": "Allocated/Promoted",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(rate(jvm_gc_memory_allocated_bytes_total{namespace='$ns', pod='$pod'}[2m]))",
     "legendFormat": "Young allocated"
    },
    {
     "expr": "avg(rate(jvm_gc_memory_promoted_bytes_total{namespace='$ns', pod='$pod'}[2m]))",
     "legendFormat": "Old promoted"
    }
   ]
  },
  { "title": "Container", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(system_cpu_usage{namespace='$ns', pod='$pod'})",
     "legendFormat": "system"
    },
    {
     "expr": "avg(process_cpu_usage{namespace='$ns', pod='$pod'})",
     "legendFormat": "process"
    },
    {
     "expr": "avg(avg_over_time(process_cpu_usage{namespace='$ns', pod='$pod'}[1h]))",
     "legendFormat": "process-1h"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(system_load_average_1m{namespace='$ns', pod='$pod'})",
     "legendFormat": "system-1m"
    },
    {
     "expr": "avg(system_cpu_count{namespace='$ns', pod='$pod'})",
     "legendFormat": "cpu_count"
    }
   ]
  },
  {
   "title": "Log Events (2m)-Error && Warn",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(log4j2_events_total{namespace='$ns',pod='$pod', level =~'error|warn'}[2m])",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Thread States",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (state) (jvm_threads_states_threads{namespace='$ns', pod='$pod'})",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "sum(jvm_threads_states_threads{namespace='$ns', pod='$pod', state=\"blocked\"})",
     "legendFormat": "block_thread"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(jvm_threads_live_threads{namespace='$ns', pod='$pod'})",
     "legendFormat": "live"
    },
    {
     "expr": " sum(jvm_threads_daemon_threads{namespace='$ns', pod='$pod'})",
     "legendFormat": "daemon"
    },
    {
     "expr": " sum(jvm_threads_peak_threads{namespace='$ns', pod='$pod'})",
     "legendFormat": "peak"
    },
    {
     "expr": "sum(jvm_threads_states_threads{namespace='$ns', pod='$pod'})",
     "legendFormat": "process"
    }
   ]
  },
  {
   "title": "Pod Restart or OOM",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 98 },
   "targets": [
    {
     "expr": "sum by (container) (increase(kube_pod_container_status_restarts_total{namespace='$ns', pod='$pod'}[10m]))",
     "legendFormat": "Restart {{container}}"
    },
    {
     "expr": "sum by (container) (increase(kube_pod_container_status_last_terminated_reason{namespace='$ns', pod='$pod', reason=\"OOMKilled\"}[10m]))",
     "legendFormat": "OOM {{container}}"
    }
   ]
  },
  { "title": "Classloading", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 107 } },
  {
   "title": "Classes loaded",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": " sum(jvm_classes_loaded_classes{namespace='$ns',pod='$pod'})",
     "legendFormat": "loaded"
    }
   ]
  },
  {
   "title": "Class delta (5m)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 108 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " sum(delta(jvm_classes_loaded_classes{namespace='$ns', pod='$pod'}[5m]))",
     "legendFormat": "delta"
    }
   ]
  },
  { "title": "Buffer Pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 115 } },
  {
   "title": "Direct Buffers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(jvm_buffer_memory_used_bytes{namespace='$ns', pod='$pod', id=\"direct\"})",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{namespace='$ns', pod='$pod', id=\"direct\"}",
     "legendFormat": "capacity"
    }
   ]
  },
  {
   "title": "Direct Buffers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_buffer_count_buffers{namespace='$ns', pod='$pod', id=\"direct\"}",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Mapped Buffers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(jvm_buffer_memory_used_bytes{namespace='$ns', pod='$pod', id=\"mapped\"})",
     "legendFormat": "used"
    },
    {
     "expr": "avg by (pod) (jvm_buffer_total_capacity_bytes{namespace='$ns', pod='$pod', id=\"mapped\"})",
     "legendFormat": "capacity"
    }
   ]
  },
  {
   "title": "Mapped Buffers count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(jvm_buffer_count_buffers{namespace='$ns', pod='$pod', id=\"mapped\"})",
     "legendFormat": "count"
    }
   ]
  }
 ]
}