{
 "title": "kcustomer",
 "description": "Dashboard for Micrometer(Java, Spring Boot, Actuator)",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pod_name",
    "label": "pod_name",
    "query": {
     "query": "label_values(container_memory_usage_bytes{container=\"kcustomer\", }, pod_name)"
    }
   },
   {
    "name": "jvm_memory_pool_heap",
    "label": "JVM Memory Pools Heap",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{pod_name=\"$pod_name\", area=\"heap\"},id)"
    }
   },
   {
    "name": "jvm_memory_pool_nonheap",
    "label": "JVM Memory Pools Non-Heap",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{pod_name=\"$pod_name\", area=\"nonheap\"},id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Quick Facts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "pod_name" },
  {
   "title": "Uptime $pod_name",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{application='kcustomer', pod_name='$pod_name'}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Start time $pod_name",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{application='kcustomer', pod_name='$pod_name'}*1000",
     "legendFormat": "Uptime_{{pod_name}}"
    }
   ]
  },
  {
   "title": "Cpu load 10s $pod_name",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "container_cpu_load_average_10s{container='kcustomer', pod_name='$pod_name'}",
     "legendFormat": "cpu_load_{{pod_name}}"
    }
   ]
  },
  {
   "title": " Heap used $pod_name",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{ area=\"heap\"})*100/sum(jvm_memory_max_bytes{ area=\"heap\"})",
     "legendFormat": "HeapUsed_$pod_name"
    }
   ]
  },
  {
   "title": "Non-Heap used $pod_name",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{ area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{ area=\"nonheap\"})",
     "legendFormat": "Non-HeapUsage_$pod_name"
    }
   ]
  },
  { "title": "JVM Memory Pools (Heap)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 }, "repeat": "pod_name" },
  {
   "title": "$jvm_memory_pool_heap $pod_name",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 20 },
   "repeat": "jvm_memory_pool_heap",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_committed_bytes{pod_name=\"$pod_name\", id=\"$jvm_memory_pool_heap\"}",
     "legendFormat": "commited"
    },
    {
     "expr": "jvm_memory_max_bytes{pod_name=\"$pod_name\", id=\"$jvm_memory_pool_heap\"}",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "JVM Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "JVM Heap",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod_name) (jvm_memory_used_bytes{application=\"kcustomer\", area=\"heap\"})",
     "legendFormat": "heap_used_{{pod_name}}"
    },
    {
     "expr": "sum by (pod_name) (jvm_memory_committed_bytes{application=\"kcustomer\", area=\"heap\"})",
     "legendFormat": "committed_{{pod_name}}"
    },
    {
     "expr": "sum by (pod_name) (jvm_memory_max_bytes{application=\"kcustomer\", area=\"heap\"})",
     "legendFormat": "max_{{pod_name}}"
    }
   ]
  },
  {
   "title": "JVM Non-Heap",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod_name)(jvm_memory_used_bytes{application='kcustomer', area=\"nonheap\"})",
     "legendFormat": "used_{{pod_name}}"
    },
    {
     "expr": "sum by (pod_name) (jvm_memory_committed_bytes{application='kcustomer', area=\"nonheap\"})",
     "legendFormat": "committed_{{pod_name}}"
    },
    {
     "expr": "sum by (pod_name) (jvm_memory_max_bytes{application='kcustomer', area=\"nonheap\"})",
     "legendFormat": "max_{{pod_name}}"
    }
   ]
  },
  {
   "title": "JVM Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod_name) (jvm_memory_used_bytes{application='kcustomer'})",
     "legendFormat": "used_{{pod_name}}"
    },
    {
     "expr": "sum by (pod_name) (jvm_memory_committed_bytes{application='kcustomer'})",
     "legendFormat": "committed_{{pod_name}}"
    },
    {
     "expr": "sum by (pod_name) (jvm_memory_max_bytes{application='kcustomer'})",
     "legendFormat": "max_{{pod_name}}"
    }
   ]
  },
  {
   "title": "Heap Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by (pod_name) (jvm_memory_used_bytes{application='kcustomer', area='heap'})* 100) /sum by (pod_name) (jvm_memory_max_bytes{application='kcustomer', area='heap'}) ",
     "legendFormat": "heap_usage_{{pod_name}}"
    }
   ]
  },
  {
   "title": "Non Heap Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by (pod_name) (jvm_memory_used_bytes{application='kcustomer', area='nonheap'})* 100) /sum by (pod_name) (jvm_memory_max_bytes{application='kcustomer', area='nonheap'}) ",
     "legendFormat": "nonheap_usage_{{pod_name}}"
    }
   ]
  },
  { "title": "JVM Memory Pools (Non-Heap)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 }, "repeat": "pod_name" },
  {
   "title": "$jvm_memory_pool_nonheap $pod_name",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 49 },
   "repeat": "jvm_memory_pool_nonheap",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{pod_name=\"$pod_name\", id=\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "used {{pod_name}}"
    },
    {
     "expr": "jvm_memory_committed_bytes{pod_name=\"$pod_name\", id=\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "commited  {{pod_name}}"
    },
    {
     "expr": "jvm_memory_max_bytes{pod_name=\"$pod_name\", id=\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "max  {{pod_name}}"
    }
   ]
  },
  { "title": "Dubbo Requests Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Dubbo Request Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum by (pod_name, interface) (increase(dubbo_request_success_total{application='kcustomer'}[2m])/120))/(sum by (pod_name, interface) (increase(dubbo_request_total{application='kcustomer'}[2m])/120))",
     "legendFormat": "{{pod_name}}_{{interface}}"
    }
   ]
  },
  {
   "title": "Dubbo Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (pod_name, interface, method) (dubbo_request_latency_seconds{application='kcustomer', quantile='0.9'}*1000)",
     "legendFormat": "{{pod_name}}_{{interface}}.{{method}}"
    }
   ]
  },
  {
   "title": "Dubbo Request Concurrent",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 59 },
   "targets": [
    {
     "expr": "sum by (pod_name, interface) (increase(dubbo_request_concurrent_total{application='kcustomer'}[2m])/120)",
     "legendFormat": "{{pod_name}}_{{interface}}"
    }
   ]
  },
  { "title": "HttpRequests Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Http Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (pod_name, uri) (rate(http_server_requests_seconds_count{application='kcustomer'}[2m]))",
     "legendFormat": "HTTP_{{pod_name}}_{{uri}}"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (pod_name, uri) (rate(http_server_requests_seconds_sum{application=\"kcustomer\", status!~\"5..\"}[2m]))/sum by (pod_name, uri) (rate(http_server_requests_seconds_count{application=\"kcustomer\", status!~\"5..\"}[2m]))",
     "legendFormat": "HTTP - AVG-  {{ pod_name}}-{{uri}}"
    },
    {
     "expr": "max by (pod_name, uri) (http_server_requests_seconds_max{application=\"kcustomer\", status!~\"5..\"})",
     "legendFormat": "HTTP - MAX  {{ pod_name}}-{{uri}}"
    }
   ]
  },
  {
   "title": "Http-Errors-5xx",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (pod_name, uri) (rate(http_server_requests_seconds_count{application=\"kcustomer\", status=~\"5..\"}[2m]))",
     "legendFormat": "HTTP - 5xx- {{pod_name}}_{{uri}}"
    }
   ]
  },
  { "title": "Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "Collections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg by (pod_name, action, cause) (rate(jvm_gc_pause_seconds_count{application=\"kcustomer\"}[2m]))",
     "legendFormat": "{{action}} ({{cause}})_{{pod_name}}"
    },
    {
     "expr": "avg by (pod_name, cause) (rate(jvm_gc_pause_seconds_count{application=\"kcustomer\", action=\"end of major GC\"}[2m]))",
     "legendFormat": "MajorGC_{{pod_name}}"
    }
   ]
  },
  {
   "title": "Pause Durations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (pod_name, action, cause) (rate(jvm_gc_pause_seconds_sum{application=\"kcustomer\"}[2m])/rate(jvm_gc_pause_seconds_count{application=\"kcustomer\"}[2m]))",
     "legendFormat": "avg {{action}} ({{cause}})_{{pod_name}}"
    },
    {
     "expr": "avg by (pod_name, action, cause) (jvm_gc_pause_seconds_max{application=\"kcustomer\"})",
     "legendFormat": "max {{action}} ({{cause}})_{{pod_name}}"
    }
   ]
  },
  {
   "title": "Allocated/Promoted",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (pod_name) (rate(jvm_gc_memory_allocated_bytes_total{application=\"kcustomer\"}[2m]))",
     "legendFormat": "Young allocated_{{pod_name}}"
    },
    {
     "expr": "avg by (pod_name) (rate(jvm_gc_memory_promoted_bytes_total{application=\"kcustomer\"}[2m]))",
     "legendFormat": "Old promoted_{{pod_name}}"
    }
   ]
  },
  { "title": "Container", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (pod_name) (system_cpu_usage{application=\"kcustomer\"})",
     "legendFormat": "system_{{pod_name}}"
    },
    {
     "expr": "avg by (pod_name) (process_cpu_usage{application=\"kcustomer\"})",
     "legendFormat": "process_{{pod_name}}"
    },
    {
     "expr": "avg by (pod_name) (avg_over_time(process_cpu_usage{application=\"kcustomer\"}[1h]))",
     "legendFormat": "process-1h_{{pod_name}}"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (pod_name) (system_load_average_1m{application='kcustomer'})",
     "legendFormat": "system-1m-{{pod_name}}"
    },
    {
     "expr": "avg by (pod_name) (system_cpu_count{application='kcustomer'})",
     "legendFormat": "cpu--{{pod_name}}"
    }
   ]
  },
  {
   "title": "Log Events (2m)-Error",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(log4j2_events_total{application='kcustomer', level =~'error|warn'}[2m])",
     "legendFormat": "{{pod_name}}_{{level}}"
    }
   ]
  },
  {
   "title": "Thread States",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod_name, state) (jvm_threads_states_threads{application='kcustomer'})",
     "legendFormat": "{{pod_name}}_{{state}}"
    },
    {
     "expr": "sum by (pod_name) (jvm_threads_states_threads{application='kcustomer', state=\"blocked\"})",
     "legendFormat": "block_thread_{{pod_name}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod_name) (jvm_threads_live_threads{application=\"kcustomer\"})",
     "legendFormat": "live_{{pod_name}}"
    },
    {
     "expr": " sum by (pod_name) (jvm_threads_daemon_threads{application=\"kcustomer\"})",
     "legendFormat": "daemon_{{pod_name}}"
    },
    {
     "expr": " sum by (pod_name) (jvm_threads_peak_threads{application=\"kcustomer\"})",
     "legendFormat": "peak_{{pod_name}}"
    },
    {
     "expr": "sum by (pod_name) (jvm_threads_states_threads{application=\"kcustomer\"})",
     "legendFormat": "process_{{pod_name}}"
    }
   ]
  },
  {
   "title": "Pod Restart or OOM",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 98 },
   "targets": [
    {
     "expr": "sum by (container) (increase(kube_pod_container_status_restarts_total{container='kcustomer'}[10m]))",
     "legendFormat": "restart {{container}}"
    },
    {
     "expr": "sum by (container) (increase(kube_pod_container_status_last_terminated_reason{container='kcustomer', reason=\"OOMKilled\"}[10m]))",
     "legendFormat": "OOM {{container}}"
    }
   ]
  },
  { "title": "Classloading", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 107 } },
  {
   "title": "Classes loaded",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": " sum by (pod_name) (jvm_classes_loaded_classes{application=\"kcustomer\"})",
     "legendFormat": "loaded_{{pod_name}}"
    }
   ]
  },
  {
   "title": "Class delta (5m)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 108 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " sum by (pod_name) (delta(jvm_classes_loaded_classes{application=\"kcustomer\"}[5m]))",
     "legendFormat": "delta_{{pod_name}}"
    }
   ]
  },
  { "title": "Buffer Pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 115 } },
  {
   "title": "Direct Buffers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (pod_name) (jvm_buffer_memory_used_bytes{application=\"kcustomer\", id=\"direct\"})",
     "legendFormat": "used_{{pod_name}}"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{application=\"kcustomer\", id=\"direct\"}",
     "legendFormat": "capacity_{{pod_name}}"
    }
   ]
  },
  {
   "title": "Direct Buffers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_buffer_count_buffers{application=\"kcustomer\", id=\"direct\"}",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Mapped Buffers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (pod_name) (jvm_buffer_memory_used_bytes{application=\"kcustomer\", id=\"mapped\"})",
     "legendFormat": "used_{{pod_name}}"
    },
    {
     "expr": "avg by (pod_name) (jvm_buffer_total_capacity_bytes{application=\"kcustomer\", id=\"mapped\"})",
     "legendFormat": "capacity_{{pod_name}}"
    }
   ]
  },
  {
   "title": "Mapped Buffers count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (pod_name) (jvm_buffer_count_buffers{application=\"kcustomer\", id=\"mapped\"})",
     "legendFormat": "count_{{pod_name}}"
    }
   ]
  }
 ]
}