{
 "title": "kfinancing",
 "description": "Dashboard for Micrometer(Java, Spring Boot, Actuator)",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(container_memory_usage_bytes{container=\"kfinancing\", }, pod)"
    }
   },
   {
    "name": "jvm_memory_pool_heap",
    "label": "JVM Memory Pools Heap",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{pod=\"$pod\", area=\"heap\"},id)"
    }
   },
   {
    "name": "jvm_memory_pool_nonheap",
    "label": "JVM Memory Pools Non-Heap",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{pod=\"$pod\", area=\"nonheap\"},id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Quick Facts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "pod" },
  {
   "title": "Uptime $pod",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{application='kfinancing', pod='$pod'}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Start time $pod",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{application='kfinancing', pod='$pod'}*1000",
     "legendFormat": "Uptime_{{pod}}"
    }
   ]
  },
  {
   "title": "Cpu load 10s $pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "container_cpu_load_average_10s{container='kfinancing', pod='$pod'}",
     "legendFormat": "cpu_load_{{pod}}"
    }
   ]
  },
  {
   "title": " Heap used $pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{ area=\"heap\"})*100/sum(jvm_memory_max_bytes{ area=\"heap\"})",
     "legendFormat": "HeapUsed_$pod"
    }
   ]
  },
  {
   "title": "Non-Heap used $pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{ area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{ area=\"nonheap\"})",
     "legendFormat": "Non-HeapUsage_$pod"
    }
   ]
  },
  { "title": "JVM Memory Pools (Heap)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 }, "repeat": "pod" },
  {
   "title": "$jvm_memory_pool_heap $pod",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 20 },
   "repeat": "jvm_memory_pool_heap",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_committed_bytes{pod=\"$pod\", id=\"$jvm_memory_pool_heap\"}",
     "legendFormat": "commited"
    },
    {
     "expr": "jvm_memory_max_bytes{pod=\"$pod\", id=\"$jvm_memory_pool_heap\"}",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "JVM Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "JVM Heap",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (jvm_memory_used_bytes{application=\"kfinancing\", area=\"heap\"})",
     "legendFormat": "heap_used_{{pod}}"
    },
    {
     "expr": "sum by (pod) (jvm_memory_committed_bytes{application=\"kfinancing\", area=\"heap\"})",
     "legendFormat": "committed_{{pod}}"
    },
    {
     "expr": "sum by (pod) (jvm_memory_max_bytes{application=\"kfinancing\", area=\"heap\"})",
     "legendFormat": "max_{{pod}}"
    }
   ]
  },
  {
   "title": "JVM Non-Heap",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod)(jvm_memory_used_bytes{application='kfinancing', area=\"nonheap\"})",
     "legendFormat": "used_{{pod}}"
    },
    {
     "expr": "sum by (pod) (jvm_memory_committed_bytes{application='kfinancing', area=\"nonheap\"})",
     "legendFormat": "committed_{{pod}}"
    },
    {
     "expr": "sum by (pod) (jvm_memory_max_bytes{application='kfinancing', area=\"nonheap\"})",
     "legendFormat": "max_{{pod}}"
    }
   ]
  },
  {
   "title": "JVM Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (jvm_memory_used_bytes{application='kfinancing'})",
     "legendFormat": "used_{{pod}}"
    },
    {
     "expr": "sum by (pod) (jvm_memory_committed_bytes{application='kfinancing'})",
     "legendFormat": "committed_{{pod}}"
    },
    {
     "expr": "sum by (pod) (jvm_memory_max_bytes{application='kfinancing'})",
     "legendFormat": "max_{{pod}}"
    }
   ]
  },
  {
   "title": "Heap Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by (pod) (jvm_memory_used_bytes{application='kfinancing', area='heap'})* 100) /sum by (pod) (jvm_memory_max_bytes{application='kfinancing', area='heap'}) ",
     "legendFormat": "heap_usage_{{pod}}"
    }
   ]
  },
  {
   "title": "Non Heap Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by (pod) (jvm_memory_used_bytes{application='kfinancing', area='nonheap'})* 100) /sum by (pod) (jvm_memory_max_bytes{application='kfinancing', area='nonheap'}) ",
     "legendFormat": "nonheap_usage_{{pod}}"
    }
   ]
  },
  { "title": "JVM Memory Pools (Non-Heap)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 }, "repeat": "pod" },
  {
   "title": "$jvm_memory_pool_nonheap $pod",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 49 },
   "repeat": "jvm_memory_pool_nonheap",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{pod=\"$pod\", id=\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "used {{pod}}"
    },
    {
     "expr": "jvm_memory_committed_bytes{pod=\"$pod\", id=\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "commited  {{pod}}"
    },
    {
     "expr": "jvm_memory_max_bytes{pod=\"$pod\", id=\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "max  {{pod}}"
    }
   ]
  },
  { "title": "Dubbo Requests Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Dubbo Request Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum by (pod, interface) (increase(dubbo_request_success_total{application='kfinancing'}[2m])/120))/(sum by (pod, interface) (increase(dubbo_request_total{application='kfinancing'}[2m])/120))",
     "legendFormat": "{{pod}}_{{interface}}"
    }
   ]
  },
  {
   "title": "Dubbo Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (pod, interface, method) (dubbo_request_latency_seconds{application='kfinancing', quantile='0.9'}*1000)",
     "legendFormat": "{{pod}}_{{interface}}.{{method}}"
    }
   ]
  },
  {
   "title": "Dubbo Request Concurrent",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 59 },
   "targets": [
    {
     "expr": "sum by (pod, interface) (increase(dubbo_request_concurrent_total{application='kfinancing'}[2m])/120)",
     "legendFormat": "{{pod}}_{{interface}}"
    }
   ]
  },
  { "title": "HttpRequests Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Http Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (pod, uri) (rate(http_server_requests_seconds_count{application='kfinancing'}[2m]))",
     "legendFormat": "HTTP_{{pod}}_{{uri}}"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (pod, uri) (rate(http_server_requests_seconds_sum{application=\"kfinancing\", status!~\"5..\"}[2m]))/sum by (pod, uri) (rate(http_server_requests_seconds_count{application=\"kfinancing\", status!~\"5..\"}[2m]))",
     "legendFormat": "HTTP - AVG-  {{ pod}}-{{uri}}"
    },
    {
     "expr": "max by (pod, uri) (http_server_requests_seconds_max{application=\"kfinancing\", status!~\"5..\"})",
     "legendFormat": "HTTP - MAX  {{ pod}}-{{uri}}"
    }
   ]
  },
  {
   "title": "Http-Errors-5xx",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (pod, uri) (rate(http_server_requests_seconds_count{application=\"kfinancing\", status=~\"5..\"}[2m]))",
     "legendFormat": "HTTP - 5xx- {{pod}}_{{uri}}"
    }
   ]
  },
  { "title": "Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "Collections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg by (pod, action, cause) (rate(jvm_gc_pause_seconds_count{application=\"kfinancing\"}[2m]))",
     "legendFormat": "{{action}} ({{cause}})_{{pod}}"
    },
    {
     "expr": "avg by (pod, cause) (rate(jvm_gc_pause_seconds_count{application=\"kfinancing\", action=\"end of major GC\"}[2m]))",
     "legendFormat": "MajorGC_{{pod}}"
    }
   ]
  },
  {
   "title": "Pause Durations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (pod, action, cause) (rate(jvm_gc_pause_seconds_sum{application=\"kfinancing\"}[2m])/rate(jvm_gc_pause_seconds_count{application=\"kfinancing\"}[2m]))",
     "legendFormat": "avg {{action}} ({{cause}})_{{pod}}"
    },
    {
     "expr": "avg by (pod, action, cause) (jvm_gc_pause_seconds_max{application=\"kfinancing\"})",
     "legendFormat": "max {{action}} ({{cause}})_{{pod}}"
    }
   ]
  },
  {
   "title": "Allocated/Promoted",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (pod) (rate(jvm_gc_memory_allocated_bytes_total{application=\"kfinancing\"}[2m]))",
     "legendFormat": "Young allocated_{{pod}}"
    },
    {
     "expr": "avg by (pod) (rate(jvm_gc_memory_promoted_bytes_total{application=\"kfinancing\"}[2m]))",
     "legendFormat": "Old promoted_{{pod}}"
    }
   ]
  },
  { "title": "Container", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (pod) (system_cpu_usage{application=\"kfinancing\"})",
     "legendFormat": "system_{{pod}}"
    },
    {
     "expr": "avg by (pod) (process_cpu_usage{application=\"kfinancing\"})",
     "legendFormat": "process_{{pod}}"
    },
    {
     "expr": "avg by (pod) (avg_over_time(process_cpu_usage{application=\"kfinancing\"}[1h]))",
     "legendFormat": "process-1h_{{pod}}"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (pod) (system_load_average_1m{application='kfinancing'})",
     "legendFormat": "system-1m-{{pod}}"
    },
    {
     "expr": "avg by (pod) (system_cpu_count{application='kfinancing'})",
     "legendFormat": "cpu--{{pod}}"
    }
   ]
  },
  {
   "title": "Log Events (2m)-Error",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(log4j2_events_total{application='kfinancing', level =~'error|warn'}[2m])",
     "legendFormat": "{{pod}}_{{level}}"
    }
   ]
  },
  {
   "title": "Thread States",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod, state) (jvm_threads_states_threads{application='kfinancing'})",
     "legendFormat": "{{pod}}_{{state}}"
    },
    {
     "expr": "sum by (pod) (jvm_threads_states_threads{application='kfinancing', state=\"blocked\"})",
     "legendFormat": "block_thread_{{pod}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (jvm_threads_live_threads{application=\"kfinancing\"})",
     "legendFormat": "live_{{pod}}"
    },
    {
     "expr": " sum by (pod) (jvm_threads_daemon_threads{application=\"kfinancing\"})",
     "legendFormat": "daemon_{{pod}}"
    },
    {
     "expr": " sum by (pod) (jvm_threads_peak_threads{application=\"kfinancing\"})",
     "legendFormat": "peak_{{pod}}"
    },
    {
     "expr": "sum by (pod) (jvm_threads_states_threads{application=\"kfinancing\"})",
     "legendFormat": "process_{{pod}}"
    }
   ]
  },
  {
   "title": "Pod Restart or OOM",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 98 },
   "targets": [
    {
     "expr": "sum by (container) (increase(kube_pod_container_status_restarts_total{container='kfinancing'}[10m]))",
     "legendFormat": "restart {{container}}"
    },
    {
     "expr": "sum by (container) (increase(kube_pod_container_status_last_terminated_reason{container='kfinancing', reason=\"OOMKilled\"}[10m]))",
     "legendFormat": "OOM {{container}}"
    }
   ]
  },
  { "title": "Classloading", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 107 } },
  {
   "title": "Classes loaded",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": " sum by (pod) (jvm_classes_loaded_classes{application=\"kfinancing\"})",
     "legendFormat": "loaded_{{pod}}"
    }
   ]
  },
  {
   "title": "Class delta (5m)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 108 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " sum by (pod) (delta(jvm_classes_loaded_classes{application=\"kfinancing\"}[5m]))",
     "legendFormat": "delta_{{pod}}"
    }
   ]
  },
  { "title": "Buffer Pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 115 } },
  {
   "title": "Direct Buffers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (pod) (jvm_buffer_memory_used_bytes{application=\"kfinancing\", id=\"direct\"})",
     "legendFormat": "used_{{pod}}"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{application=\"kfinancing\", id=\"direct\"}",
     "legendFormat": "capacity_{{pod}}"
    }
   ]
  },
  {
   "title": "Direct Buffers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_buffer_count_buffers{application=\"kfinancing\", id=\"direct\"}",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Mapped Buffers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (pod) (jvm_buffer_memory_used_bytes{application=\"kfinancing\", id=\"mapped\"})",
     "legendFormat": "used_{{pod}}"
    },
    {
     "expr": "avg by (pod) (jvm_buffer_total_capacity_bytes{application=\"kfinancing\", id=\"mapped\"})",
     "legendFormat": "capacity_{{pod}}"
    }
   ]
  },
  {
   "title": "Mapped Buffers count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (pod) (jvm_buffer_count_buffers{application=\"kfinancing\", id=\"mapped\"})",
     "legendFormat": "count_{{pod}}"
    }
   ]
  }
 ]
}