{
 "title": "kweb-node",
 "description": "Dashboard for Micrometer(Java, Spring Boot, Actuator)",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(container_memory_usage_bytes{container=\"kweb-node\", }, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(container_memory_usage_bytes{container=\"kweb-node\",namespace=\"$namespace\" }, pod)"
    }
   },
   {
    "name": "jvm_memory_pool_heap",
    "label": "JVM Memory Pools Heap",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{pod=\"$pod\", area=\"heap\"},id)"
    }
   },
   {
    "name": "jvm_memory_pool_nonheap",
    "label": "JVM Memory Pools Non-Heap",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{pod=\"$pod\", area=\"nonheap\"},id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Quick Facts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "pod" },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{service=\"kweb-node\", pod='$pod'}*1000",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{service=\"kweb-node\", pod='$pod'}*1000",
     "legendFormat": "Uptime_{{pod}}"
    }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds{pod=~\"$pod\"}",
     "legendFormat": "$pod"
    }
   ]
  },
  { "title": "HttpRequests Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Http Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (pod, path) (rate(social_http_request_duration_milliseconds_count{service=\"kweb-node\"}[2m]))",
     "legendFormat": "HTTP_{{pod}}_{{path}}"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (pod, path) (rate(social_http_request_duration_milliseconds_sum{service=\"kweb-node\", status!~\"5..\"}[2m]))/sum by (pod, path) (rate(social_http_request_duration_milliseconds_count{service=\"kweb-node\", status!~\"5..\"}[2m]))",
     "legendFormat": "HTTP - AVG-  {{ pod}}-{{path}}"
    }
   ]
  },
  {
   "title": "Http-Errors-5xx",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (pod, path) (rate(social_http_all_fail_total{service=\"kweb-node\",status=~\"5..\"}[2m]))",
     "legendFormat": "HTTP - 5xx- {{pod}}_{{path}}"
    }
   ]
  },
  { "title": "Container", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Process CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_user_seconds_total{pod=~\"$pod\"}[2m]) ",
     "legendFormat": "User CPU  - $pod"
    },
    {
     "expr": "irate(process_cpu_system_seconds_total{pod=~\"$pod\"}[2m])",
     "legendFormat": "Sys CPU  - $pod"
    }
   ]
  },
  {
   "title": "Process Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{pod=~\"$pod\"}",
     "legendFormat": "Process Memory  - $pod"
    },
    {
     "expr": "nodejs_heap_size_total_bytes{pod=~\"$pod\"}",
     "legendFormat": "Heap Total - $pod"
    },
    {
     "expr": "nodejs_heap_size_used_bytes{pod=~\"$pod\"}",
     "legendFormat": "Heap Used - $pod"
    },
    {
     "expr": "nodejs_external_memory_bytes{pod=~\"$pod\"}",
     "legendFormat": "External Memory - $pod"
    },
    {
     "expr": "process_virtual_memory_bytes{pod=~\"$pod\"}",
     "legendFormat": "Process Virtual Memory  - $pod"
    }
   ]
  },
  {
   "title": "Pod Restart or OOM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (container) (increase(kube_pod_container_status_restarts_total{pod='$pod'}[10m]))",
     "legendFormat": "restart - $pod"
    }
   ]
  },
  {
   "title": "process_fds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "process_max_fds{pod='$pod'}", "legendFormat": "restart - $pod" },
    { "expr": "process_open_fds  {pod='$pod'}", "legendFormat": "restart - $pod" }
   ]
  },
  { "title": "Heap Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Heap Total Detail",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_space_size_total_bytes{pod=~\"$pod\"}",
     "legendFormat": "Heap Total - $pod - {{space}}"
    }
   ]
  },
  {
   "title": "Heap Used Detail",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_space_size_used_bytes{pod=~\"$pod\"}",
     "legendFormat": "Heap Used - $pod - {{space}}"
    }
   ]
  },
  {
   "title": "Heap Available Detail",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_space_size_available_bytes{pod=~\"$pod\"}",
     "legendFormat": "Heap Total - $pod - {{space}}"
    }
   ]
  },
  {
   "title": "nodejs_active",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nodejs_active_handles{pod='$pod'}",
     "legendFormat": "restart - $pod"
    },
    {
     "expr": "nodejs_active_handles_total{pod='$pod'}",
     "legendFormat": "restart - $pod"
    },
    {
     "expr": "nodejs_active_requests_total{pod='$pod'}",
     "legendFormat": "restart - $pod"
    }
   ]
  }
 ]
}