{
 "title": "Ignite-Cluster",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "query": { "query": "sys_UpTime" } }
  ]
 },
 "panels": [
  {
   "title": "Sys Heap Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sys_memory_heap_used/sys_memory_heap_max",
     "legendFormat": "Sys Heap Usage {{job}}"
    }
   ]
  },
  {
   "title": "Sys CpuLoad",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "sys_CpuLoad", "legendFormat": "CpuLoad_{{job}}" }
   ]
  },
  {
   "title": "Baseline nodes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (job) (cluster_ActiveBaselineNodes)",
     "legendFormat": "ActiveBaselineNodes_{{job}}"
    },
    {
     "expr": "sum by (job) (cluster_TotalBaselineNodes)",
     "legendFormat": "TotalBaselineNodes_{{job}}"
    },
    {
     "expr": "sum by (job) (cluster_TotalBaselineNodes-cluster_ActiveBaselineNodes)",
     "legendFormat": "DiffBaselineNodes_{{job}}"
    },
    {
     "expr": "sum by (job) (cluster_TotalServerNodes) ",
     "legendFormat": "TotalServerNodes_{{job}}"
    }
   ]
  },
  {
   "title": "sys_ThreadCount",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "sys_ThreadCount", "legendFormat": "sys_ThreadCount_{{job}}" }
   ]
  },
  {
   "title": "sys_memory_heap(MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sys_memory_heap_max/1000/1000/1000",
     "legendFormat": "heap_max_{{job}}"
    },
    { "expr": "sys_memory_heap_used/1000/1000", "legendFormat": "heap_used_{{job}}" }
   ]
  }
 ]
}