{
 "title": "Ignite-Storage",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "query": { "query": "sys_UpTime" } }
  ]
 },
 "panels": [
  {
   "title": "StorageSize(MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "io_datastorage_StorageSize", "legendFormat": "StorageSize_{{job}}" }
   ]
  },
  {
   "title": "StorageWalTotalSize(MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "io_datastorage_WalTotalSize", "legendFormat": "WalTotalSize_{{job}}" }
   ]
  },
  {
   "title": "StorageWalWritingRate(MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "io_datastorage_WalWritingRate{job='$instance'}/1000/1000"
    }
   ]
  },
  {
   "title": "StorageCheckpointFsyncHistogram",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "io_datastorage_CheckpointFsyncHistogram_0_100"
    },
    {
     "expr": "io_datastorage_CheckpointWalRecordFsyncHistogram_1000_5000"
    },
    {
     "expr": "io_datastorage_CheckpointFsyncHistogram_500_1000"
    }
   ]
  }
 ]
}