{
 "title": "Ignite-ThreadPool",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "query": { "query": "sys_UpTime" } }
  ]
 },
 "panels": [
  {
   "title": "application threadPools_GridExecutionExecutor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "krisk_threadPools_GridExecutionExecutor_QueueSize",
     "legendFormat": "Krisk_GridExecutionExecutor_{{pod_name}}"
    },
    {
     "expr": "knotify_threadPools_GridExecutionExecutor_QueueSize",
     "legendFormat": "Krisk_GridExecutionExecutor_{{pod_name}}"
    },
    {
     "expr": "dtm_threadPools_GridExecutionExecutor_QueueSize",
     "legendFormat": "Krisk_GridExecutionExecutor_{{pod_name}}"
    }
   ]
  },
  {
   "title": "GridQueryExecutor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "threadPools_GridQueryExecutor_PoolSize",
     "legendFormat": "GridQueryExecutor_PoolSize_{{job}}"
    },
    {
     "expr": "threadPools_GridQueryExecutor_MaximumPoolSize",
     "legendFormat": "GridQueryExecutor_MaximumPoolSize_{{job}}"
    },
    {
     "expr": "threadPools_GridQueryExecutor_QueueSize",
     "legendFormat": "GridQueryExecutor_QueueSize_{{job}}"
    }
   ]
  },
  {
   "title": "DataStreamExecutor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "threadPools_GridDataStreamExecutor_ActiveCount",
     "legendFormat": "DataStrean_ActiveCount_{{job}}"
    },
    {
     "expr": "threadPools_GridDataStreamExecutor_TotalQueueSize",
     "legendFormat": "DataStrean_TotalQueueSize_{{job}}"
    }
   ]
  },
  {
   "title": "GridSystemExecutor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "threadPools_GridSystemExecutor_PoolSize",
     "legendFormat": "GridSystemExecutor_PoolSize_{{job}}"
    },
    {
     "expr": "threadPools_GridSystemExecutor_MaximumPoolSize",
     "legendFormat": "GridSystemExecutor_MaximumPoolSize_{{job}}"
    },
    {
     "expr": "threadPools_GridSystemExecutor_QueueSize",
     "legendFormat": "GridSystemExecutor_QueueSize_{{job}}"
    }
   ]
  },
  {
   "title": "GridCallbackExecutor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "threadPools_GridCallbackExecutor_PoolSize",
     "legendFormat": "GridCallbackExecutor_PoolSize_{{job}}"
    },
    {
     "expr": "threadPools_GridCallbackExecutor_MaximumPoolSize",
     "legendFormat": "GridCallbackExecutor_MaximumPoolSize_{{job}}"
    },
    {
     "expr": "threadPools_GridCallbackExecutor_QueueSize",
     "legendFormat": "GridCallbackExecutor_QueueSize_{{job}}"
    }
   ]
  },
  {
   "title": "GridExecutionExecutor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "threadPools_GridExecutionExecutor_PoolSize",
     "legendFormat": "GridExecutionExecutor_PoolSize_{{job}}"
    },
    {
     "expr": "threadPools_GridExecutionExecutor_MaximumPoolSize",
     "legendFormat": "GridExecutionExecutor_MaximumPoolSize_{{job}}"
    },
    {
     "expr": "threadPools_GridExecutionExecutor_QueueSize",
     "legendFormat": "GridExecutionExecutor_QueueSize_{{job}}"
    }
   ]
  }
 ]
}